package com.example.project1_438.database

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.PrimaryKey

@Entity
data class User (
//    This will be autogenerated and never changed, so we use a val,
//    It autogens when the value of the long is 0
    @PrimaryKey(autoGenerate = true) val userId: Long = 0,
//    These will be user generated and possibly changed, so we'll use vars
    @ColumnInfo(name = "userName") var userName: String,
    @ColumnInfo(name = "firstName") var firstName: String,
    @ColumnInfo(name = "lastName") var lastName: String,
    @ColumnInfo(name = "password") var password: String
)


