package com.example.project1_438.database

import androidx.room3.Dao
import androidx.room3.Delete
import androidx.room3.Insert
import androidx.room3.Query

// This is the file where we put the Query Functions for the database to add, retrieve, or delete data
@Dao
interface UserDao {
//    The query to just grab all co,uns from the User table, if needed
    @Query("SELECT * FROM User")
//    The suspend keyword lets the function be paused and resumed later once it gets a response
    suspend fun getAllUsers(): List<User>

//    Allows us to grab all users and list them by ID value
    @Query("SELECT * FROM User Where userId IN (:userIds) ORDER BY userId")
    suspend fun loadAllByIds(userIds: LongArray): List<User>

//    Grab a single user by their ID
    @Query("SELECT * FROM User WHERE userId = :userId")
    suspend fun getUserById(userId: Long): User? // <Val>? lets our function return either a value or null

//    Gets a user by their username
    @Query("SELECT * FROM User WHERE userName = :userName LIMIT 1")
    suspend fun getUserByUserName(userName: String): User?

    //gets user if username and password is in db
    @Query(
        "SELECT * FROM User WHERE userName = :userName AND password = :password LIMIT 1"
    )
    suspend fun login(userName: String, password: String): User?
//    Our Insertion Functions
//    This adds multiple users in one go
    @Insert
    suspend fun insertUsers(users: List<User>)

//    Inserting one user
    @Insert
//    suspend fun insertUser(user: User) // This doesn't match the autogenerated variable type of long
    suspend fun insertUser(user: User): Long // This returns a Long, which is what the Room API generates

//    Delete Function (most databases don't actually use this, they just tag a value as deleted to retrieve if needed)
    @Delete
    suspend fun deleteUser(user: User)
}