package com.example.project1_438

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.PrimaryKey

@Entity
data class User (
//    This will be autogenerated and never changed, so we use a val
    @PrimaryKey val userId: Int,
//    These will be user generated and possibly changed, so we'll use vars
    @ColumnInfo(name = "User_Name") var userName: String,
    @ColumnInfo(name = "Password") var password: String
)


